Commit
aphtoken/aph-mobile-wallet pull request #18
Opened 2018-09-13 03:43 UTC by crishellco

## Ticket
* n/a

## Changes
* Add commit view
* Merge in new icons
* Merge in dex.js, assets.js
* Fix some language references

## Screenshots
![image](https://user-images.githubusercontent.com/1878509/45465959-d5239100-b6d4-11e8-8a4b-b53b4a538c84.png)
![image](https://user-images.githubusercontent.com/1878509/45465967-dd7bcc00-b6d4-11e8-8f0f-023282466bae.png)
![image](https://user-images.githubusercontent.com/1878509/45465970-e2d91680-b6d4-11e8-9c3b-33bffdc899e4.png)

## Code Coverage
n/a

2018-09-18 06:02 UTC, jsolman commented
Issues:
1. Blocks until eligible for fees is showing a negative number instead of showing how many blocks until eligible to compound after eligible to commit. Also if already eligible to compound it should just say it is eligible to compound.
2. Compound button is able to be clicked even when it is grayed out
3. Max button on commit dialog doesn't work

Asside from those issues it looks to be working reasonably well.

2018-09-20 00:13 UTC, schaeferCode commented on src/components/AuthenticatedWrapper.vue
> +      // justify-content: center;
Is this left for some reason?

2018-09-20 00:19 UTC, schaeferCode commented on src/components/AuthenticatedWrapper.vue
> +          &.ico {
Should this be `.icon`?

2018-09-20 00:20 UTC, schaeferCode commented on src/components/Commit.vue
> +
Remove extra lines.

2018-09-20 00:34 UTC, schaeferCode commented on src/main.js
> +    //
This is coming later?

2018-09-20 00:36 UTC, schaeferCode approved these changes
Looks good so far. Just a few minor comments. I'm going to pull the branch down and mess with it some too. 

NOTES: 
I just pulled down the PR. I get a ton of warnings about `SOME_WORD` is not a string. I think these have to do with the translate tool we're using. I'm assuming we'll fill those in later? 

<img width="420" alt="screen shot 2018-09-19 at 8 42 10 pm" src="https://user-images.githubusercontent.com/28928299/45789234-9baad280-bc4c-11e8-9bfb-56c1f1bbfb4d.png">

There's no way to cancel or exit this modal once it pops up. Can easily be fixed in a later PR though. 

Everything looks great though!

2018-09-20 07:27 UTC, crishellco commented on src/components/AuthenticatedWrapper.vue
> +          &.ico {
Nope

2018-09-20 07:35 UTC, crishellco commented
@schaeferCode 
![screen shot 2018-09-20 at 1 33 48 am](https://user-images.githubusercontent.com/1878509/45802916-61a1f680-bc75-11e8-913a-cdbd0497533c.png)

2018-09-21 23:23 UTC, jsolman requested changes

2018-09-21 23:23 UTC, jsolman commented on src/l10n/en.json
> -  "totalBalance": "Total Balance",
Why is this removed? This is used.
Need to be verify careful with merging over translation strings.

2018-09-21 23:23 UTC, jsolman commented on src/l10n/en.json
> -  "totalBalance": "Total Balance",
Please audit to make sure other removed strings aren't being used.

2018-09-24 17:47 UTC, jsolman approved these changes

2018-09-24 17:48 UTC, merged